name: CI workflow

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  # unit-test:
  #   runs-on: ubuntu-latest
  #   name: Run Unit Test
  #   steps:
  #     - id: foo
  #       uses: huynamboz/ci-cd-training/.github/quality@v1
  call-reusable-workflow:
    uses: ./.github/workflows/test_workflow.yml
    with:
      branch: 'develop'
      run-tests: true